version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports: 
      - "8081:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - place-bids
      - get-bids
  place-bids:
    container_name: placebids
    build: .
    environment: 
      - MONGO_URI="mongodb://db:27017"
    depends_on: 
      - db
  get-bids:
    container_name:  getbids
    build: .
    environment: 
      - MONGO_URI="mongodb://db:27017"
    depends_on: 
      - db
  db:
    container_name: db
    image: mongo
